# Generated by Django 3.2.6 on 2021-08-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='../static/images/user-default.png', upload_to=''),
        ),
    ]
