# Generated by Django 3.2.4 on 2021-06-24 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_text', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('idea_likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugg_text', models.CharField(max_length=300)),
                ('sugg_likes', models.IntegerField(default=0)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_idea', to='ideabook.idea')),
            ],
        ),
    ]
