# Generated by Django 3.2.4 on 2021-06-28 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ideabook', '0002_alter_suggestion_idea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='idea',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date posted'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestion',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date posted'),
            preserve_default=False,
        ),
    ]
