# Generated by Django 3.2.6 on 2021-08-12 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideabook', '0003_auto_20210629_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='post_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='auth.user'),
            preserve_default=False,
        ),
    ]
