# Generated by Django 3.2.6 on 2021-08-12 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideabook', '0004_idea_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='post_user',
        ),
    ]
