# Generated by Django 3.2.6 on 2021-08-13 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideabook', '0005_remove_idea_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='post_date',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='post_date',
        ),
        migrations.AddField(
            model_name='idea',
            name='idea_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date idea posted'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='idea_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='idea', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestion',
            name='sugg_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date sugg posted'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestion',
            name='sugg_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sugg', to='auth.user'),
            preserve_default=False,
        ),
    ]
