# Generated by Django 3.2.6 on 2021-08-14 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideabook', '0006_auto_20210813_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='idea_likes',
        ),
        migrations.AddField(
            model_name='idea',
            name='idea_likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='likers', to=settings.AUTH_USER_MODEL, verbose_name='people who liked'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='idea_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
